displayName=Logout Fix Resizable Modern
author=Cait
description=Change the resizable modern logout button to be in the same spot as in fix classic
tags=logout,resizable,modern,ui
plugins=com.LogoutFixResizableModern.LogoutFixResizableModernPlugin
build=standard